/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RoadmapIndexImport } from './routes/roadmap/index'

// Create/Update Routes

const RoadmapIndexRoute = RoadmapIndexImport.update({
  id: '/roadmap/',
  path: '/roadmap/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/roadmap/': {
      id: '/roadmap/'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/roadmap': typeof RoadmapIndexRoute
}

export interface FileRoutesByTo {
  '/roadmap': typeof RoadmapIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/roadmap/': typeof RoadmapIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/roadmap'
  fileRoutesByTo: FileRoutesByTo
  to: '/roadmap'
  id: '__root__' | '/roadmap/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  RoadmapIndexRoute: typeof RoadmapIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  RoadmapIndexRoute: RoadmapIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/roadmap/"
      ]
    },
    "/roadmap/": {
      "filePath": "roadmap/index.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
